### ISSUE TITLE
VCF contains duplicates

### ISSUE THREAD

**Issue by bjhall** [bjhall/nextflow_wgs#8]
For some reason the merged VCFs from sentieon sometimes  contain duplicates. These need to be removed.

One possible solution: after gvcf_combine, add a step which uses vcfstreamsort and vcfuniq to get rid of duplicates.

**Comment by ViktorHy** [comment]
Solved by two-step process
vcfstreamsort + vcfuniq 
and added -u flag to bedtools intersect
